# SPDX-License-Identifier: GPL-3.0-or-later
"""pww_geogebra.py -- every catalogue formula in GeoGebra input syntax.

GEOGEBRA[id] is what the app's GeoGebra tab shows and copies. Every entry
was checked in GeoGebra itself (the 5.0 web app): it parses, and every
identity written with "=" that GeoGebra's CAS can simplify was confirmed
by it; the geometry relations were evaluated on real figures.

Conventions:

* Identities and equations in letters (a, b, n, theta ...) are written for
  the CAS view, where they stay symbolic. Typing an identity there, or
  Simplify(lhs - rhs), gives back what the formula claims.
* Several formulas, a formula with its conditions, a chain a = b = c, or
  "A therefore B" become a list: {a = b, b = c}. GeoGebra has no "=>".
* Ellipses become Sum(term, k, from, to). Triangular numbers T_k are
  written out as k (k + 1) / 2, so GeoGebra can evaluate them. Other
  sequences are functions of their index, F(n), t(n), X(i), which the CAS
  keeps symbolic (an indexed name like F_k would not follow the summation
  index).
* Relations between points (A, B, P ...) use GeoGebra's geometry commands
  and the comparison ==: Distance, Angle, Area, AreCollinear, AreConcyclic,
  AreParallel, ArePerpendicular, AreConcurrent. In a construction that has
  those points they come out true or false. (A plain "=" with a command on
  the left would define a function there instead.)
* Angle(X, V, Y) in GeoGebra is measured counterclockwise and can be
  reflex. A non-reflex angle is written Min(Angle(X, V, Y), Angle(Y, V, X)).
  The inscribed-angle relations keep GeoGebra's oriented angles, with the
  points listed counterclockwise.
* GCD, Mod and Divisors are meant for whole numbers (sliders): the CAS
  treats letters as polynomials there.
* A statement GeoGebra has no notation for (irrational, countable ...) is
  given as a text object, so it still pastes without an error; TEXT_ONLY
  lists those entries.
"""

GEOGEBRA: dict[str, str] = {
    # ---- A. Pythagoras and right triangles
    "A1": "{(a + b)^2 = c^2 + 4 (1/2) a b, a^2 + b^2 = c^2}",
    "A2": "{c^2 = (b - a)^2 + 4 (1/2) a b, (b - a)^2 + 4 (1/2) a b = a^2 + b^2}",
    "A3": "{a^2 = c p, b^2 = c q, p + q = c}",
    "A4": "a^2 + b^2 = c^2",
    "A5": "(1/2) (a + b)^2 = 2 (1/2) a b + (1/2) c^2",
    "A6": "{a^2 = c p, b^2 = c q, a^2 + b^2 = c (p + q), c (p + q) = c^2}",
    "A7": "c^2 = a^2 + b^2 - 2a b cos(C)",
    "A8": "r = (a + b - c) / 2",
    "A9": "a^2 + b^2 = c^2",
    "A10": "a^2 + b^2 = c^2",
    "A11": "a^2 + b^2 + 2 (1/2) a b = c^2 + 2 (1/2) a b",
    "A12": "{b^2 = (c - a) (c + a), (c - a) (c + a) = c^2 - a^2}",
    "A13": "Area(P) + Area(Q) == Area(R)",
    "A14": "k a^2 + k b^2 = k c^2",
    "A15": "L_1 + L_2 = (1/2) a b",
    "A16": "1 / a^2 + 1 / b^2 = 1 / h^2",
    "A17": "k a^2 + k b^2 = k c^2",
    "A18": "a^2 + b^2 = c^2",
    "A19": "b^2 = a^2 + c^2 - 2a c cos(B)",
    "A20": "{c^2 = a^2 + b^2 - 2a b cos(C), C > 90°}",
    "A21": "d_1^2 + d_2^2 = 2 (a^2 + b^2)",
    "A22": "a b / 2 = ((a + b - c) / 2) ((a + b + c) / 2)",
    "A23": "{c^2 = (b - a)^2 + 2a b, (b - a)^2 + 2a b = a^2 + b^2}",
    "A24": "a^2 / 2 + b^2 / 2 = c c / 2",
    "A25": "h^2 = p q",
    "A26": "{c^2 = 3a b + (b - a)^2, 3a b + (b - a)^2 = a^2 + a b + b^2}",
    "A27": "c c = a a + b b",

    # ---- B. Sums, series and figurate numbers
    "B1": "Sum(k, k, 1, n) = n (n + 1) / 2",
    "B2": "Sum(2k - 1, k, 1, n) = n^2",
    "B3": "Sum(k^2, k, 1, n) = n (n + 1) (2n + 1) / 6",
    "B4": "Sum(k^3, k, 1, n) = (n (n + 1) / 2)^2",
    "B5": "Sum(1 / 2^k, k, 1, ∞) = 1",
    "B6": "Sum(1 / 4^k, k, 1, ∞) = 1/3",
    "B7": "{Sum(r^k, k, 0, ∞) = 1 / (1 - r), abs(r) < 1}",
    "B8": "Sum(k (k + 1) / 2, k, 1, n) = n (n + 1) (n + 2) / 6",
    "B9": "Sum(F(k)^2, k, 1, n) = F(n) F(n + 1)",
    "B10": "Sum(F(k), k, 1, n) = F(n + 2) - 1",
    "B11": "Sum(BinomialCoefficient(k, r), k, r, n) = BinomialCoefficient(n + 1, r + 1)",
    "B12": "Sum(BinomialCoefficient(n, k), k, 0, n) = 2^n",
    "B13": "2 Sum(k, k, 1, n) = n (n + 1)",
    "B14": "Sum(2k, k, 1, n) = n (n + 1)",
    "B15": "3 Sum(k^2, k, 1, n) = (2n + 1) (n (n + 1) / 2)",
    "B16": "(n - 1) n / 2 + n (n + 1) / 2 = n^2",
    "B17": "8 (n (n + 1) / 2) + 1 = (2n + 1)^2",
    "B18": "Sum(k, k, 1, n) + Sum(k, k, 1, n - 1) = n^2",
    "B19": "Sum((-1)^(n - k) k^2, k, 1, n) = n (n + 1) / 2",
    "B20": "Sum(2^k, k, 0, n - 1) = 2^n - 1",
    "B21": "Sum(1 / 4^k, k, 1, ∞) = 1/3",
    "B22": "Sum(1 / 3^k, k, 1, ∞) = 1/2",
    "B23": "Sum(a + k d, k, 0, n - 1) = n (2a + (n - 1) d) / 2",
    "B24": "Sum(k / 2^k, k, 1, ∞) = 2",
    "B25": "Sum(1 / (k (k + 1)), k, 1, ∞) = 1",
    "B26": "n^3 = Sum(n^2 - n + 2k - 1, k, 1, n)",
    "B27": "{P_n = n (3n - 1) / 2, n (3n - 1) / 2 = n^2 + (n - 1) n / 2}",
    "B28": "{H_n = n (2n - 1), n (2n - 1) = (2n - 1) (2n) / 2}",
    "B29": "Sum(3k (k - 1) + 1, k, 1, n) = n^3",
    "B30": "(a + b) (a + b + 1) / 2 = a (a + 1) / 2 + b (b + 1) / 2 + a b",
    "B31": "a b (a b + 1) / 2 = (a (a + 1) / 2) (b (b + 1) / 2) + ((a - 1) a / 2) ((b - 1) b / 2)",
    "B32": "2n (2n + 1) / 2 = 3 (n (n + 1) / 2) + (n - 1) n / 2",
    "B33": "Sum(2k - 1, k, 1, n) / Sum(2k - 1, k, n + 1, 2n) = 1/3",
    "B34": "Sum(1 / k, k, 1, ∞) = ∞",
    "B35": "Sum(1 / k^2, k, 1, ∞) < 2",
    "B36": "F(n - 1) F(n + 1) - F(n)^2 = (-1)^n",
    "B37": "{Sum(F(2k - 1), k, 1, n) = F(2n), Sum(F(2k), k, 1, n) = F(2n + 1) - 1}",
    "B38": "Sum(3^k, k, 0, n - 1) = (3^n - 1) / 2",
    "B39": "Sum((-1/2)^k, k, 0, ∞) = 2/3",
    "B40": "Sum(2 / (k (k + 1)), k, 1, ∞) = 2",
    "B41": "{Sum(k r^k, k, 1, ∞) = r / (1 - r)^2, 0 < r < 1}",
    "B42": "Sum(k, k, 1, n) = n^2 / 2 + n / 2",
    "B43": "C_n = n^2 + (n - 1)^2",
    "B44": "Sum(2k - 1, k, 1, n) = n^2",
    "B45": "Sum(m + j, j, 0, k - 1) = k (2m + k - 1) / 2",
    "B46": "{A_{∞} = A (1 + (1/3) (1 / (1 - 4/9))), A (1 + (1/3) (1 / (1 - 4/9))) = (8/5) A}",
    "B47": "(1/4) Sum((3/4)^k, k, 0, ∞) = 1",
    "B48": "(1/3) Sum((2/3)^k, k, 0, ∞) = 1",
    "B49": "Sum(1 / 2^k, k, 1, ∞) = 1",

    # ---- C. Algebraic identities
    "C1": "(a + b)^2 = a^2 + 2a b + b^2",
    "C2": "(a - b)^2 = a^2 - 2a b + b^2",
    "C3": "a^2 - b^2 = (a + b) (a - b)",
    "C4": "(a + b)^3 = a^3 + 3a^2 b + 3a b^2 + b^3",
    "C5": "a^3 - b^3 = (a - b) (a^2 + a b + b^2)",
    "C6": "a (b + c) = a b + a c",
    "C7": "x^2 + b x = (x + b / 2)^2 - b^2 / 4",
    "C8": "(a + b)^2 - (a - b)^2 = 4a b",
    "C9": "(a + b)^2 + (a - b)^2 = 2 (a^2 + b^2)",
    "C10": "(a + b + c)^2 = a^2 + b^2 + c^2 + 2a b + 2b c + 2c a",
    "C11": "{a^3 + b^3 = (a + b)^3 - 3a b (a + b), (a + b)^3 - 3a b (a + b) = (a + b) (a^2 - a b + b^2)}",
    "C12": "(a + b) (c + d) = a c + a d + b c + b d",
    "C13": "x^2 + (p + q) x + p q = (x + p) (x + q)",
    "C14": "{x^2 + 10x = 39, (x + 5)^2 = 64, x = 3}",
    "C15": "a b = ((a + b) / 2)^2 - ((a - b) / 2)^2",
    "C16": "(n + 1)^3 - n^3 = 3n^2 + 3n + 1",
    "C17": "(a^2 + b^2) (c^2 + d^2) = (a c - b d)^2 + (a d + b c)^2",
    "C18": "a^4 + 4b^4 = (a^2 + 2b^2 + 2a b) (a^2 + 2b^2 - 2a b)",
    "C19": "a b = b a",
    "C20": "a^2 - b^2 = (a + b) (a - b)",
    "C21": "n^2 = (n - 1) (n + 1) + 1",
    "C22": "1/2 + 1/3 + 1/6 = 1",
    "C23": "a^4 - b^4 = (a^2 + b^2) (a + b) (a - b)",

    # ---- D. Inequalities
    "D1": "(a + b) / 2 ≥ sqrt(a b)",
    "D2": "{sqrt((a^2 + b^2) / 2) ≥ (a + b) / 2, (a + b) / 2 ≥ sqrt(a b), sqrt(a b) ≥ 2a b / (a + b)}",
    "D3": "abs((u_1, u_2) * (v_1, v_2)) ≤ abs((u_1, u_2)) abs((v_1, v_2))",
    "D4": "abs((u_1, u_2) + (v_1, v_2)) ≤ abs((u_1, u_2)) + abs((v_1, v_2))",
    "D5": "{x + 1 / x ≥ 2, x > 0}",
    "D6": "{a ≥ b, x ≥ y, a x + b y - (a y + b x) = (a - b) (x - y), (a - b) (x - y) ≥ 0}",
    "D7": "(a + b) / 2 ≥ sqrt(a b)",
    "D8": "a^2 + b^2 ≥ 2a b",
    "D9": "{2a b / (a + b) ≤ sqrt(a b), sqrt(a b) ≤ (a + b) / 2, (a + b) / 2 ≤ sqrt((a^2 + b^2) / 2)}",
    "D10": "1 / h = 1 / a + 1 / b",
    "D11": "a b ≤ ((a + b) / 2)^2",
    "D12": "{a b ≤ Integral(f(x), x, 0, a) + Integral(g(y), y, 0, b), g(f(x)) = x}",
    "D13": "f(t x + (1 - t) y) ≤ t f(x) + (1 - t) f(y)",
    "D14": "ℯ^x ≥ 1 + x",
    "D15": "{ln(x) ≤ x - 1, x > 0}",
    "D16": "π^ℯ < ℯ^π",
    "D17": "{1 / b < (ln(b) - ln(a)) / (b - a) < 1 / a, 0 < a < b}",
    "D18": "ln(n + 1) < Sum(1 / k, k, 1, n) < 1 + ln(n)",
    "D19": "{n ln(n) - n + 1 < ln(n!) < (n + 1) ln(n + 1) - n, n ≥ 2}",
    "D20": "{a / b < c / d, a / b < (a + c) / (b + d) < c / d, b > 0, d > 0}",
    "D21": "{Distance(A, P) + Distance(P, B) == Distance(A, P) + Distance(P, B'), Distance(A, P) + Distance(P, B') ≥ Distance(A, B')}",
    "D22": "abs(sin(x) - sin(y)) ≤ abs(x - y)",
    "D23": "{Sum(X(i), i, 1, n) / n ≥ nroot(Product(X(i), i, 1, n), n), X(i) > 0}",
    "D24": "{x / (1 + x) < ln(1 + x) < x, x > -1, x ≠ 0}",
    "D25": "sqrt(a) + sqrt(b) ≥ sqrt(a + b)",
    "D26": "sqrt(a^2 + b^2) + sqrt(c^2 + d^2) ≥ sqrt((a + c)^2 + (b + d)^2)",
    "D27": "{(a + b) (1 / a + 1 / b) ≥ 4, a > 0, b > 0}",
    "D28": "a b + b c + c a ≤ a^2 + b^2 + c^2",

    # ---- E. Circles and conics
    "E1": "{A = (1/2) (2π r) r, (1/2) (2π r) r = π r^2}",
    "E2": "{A = (1/2) (2π r) r, (1/2) (2π r) r = π r^2}",
    "E3": "Angle(A, B, C) == (1/2) Angle(A, O, C)",
    "E4": "Min(Angle(A, C, B), Angle(B, C, A)) == 90°",
    "E5": "Distance(P, A) Distance(P, B) == Distance(P, C) Distance(P, D)",
    "E6": "Distance(P, T)^2 == Distance(P, A) Distance(P, B)",
    "E7": "Distance(A, C) Distance(B, D) == Distance(A, B) Distance(C, D) + Distance(B, C) Distance(A, D)",
    "E8": "A = π a b",
    "E9": "A = π (L / 2)^2",
    "E10": "A = (4/3) A_{triangle}",
    "E11": "A = (1/2) r^2 θ",
    "E12": "Angle(A, C, B) == (1/2) Angle(A, O, B)",
    "E13": "θ = (α + β) / 2",
    "E14": "θ = (α - β) / 2",
    "E15": "Min(Angle(D, A, B), Angle(B, A, D)) + Min(Angle(B, C, D), Angle(D, C, B)) == 180°",
    "E16": "Distance(P, A) == Distance(P, B)",
    "E17": "Distance(P, F) == Distance(P, D)",
    "E18": "Distance(P, F_1) + Distance(P, F_2) == 2a",
    "E19": "abs(Distance(P, F_1) - Distance(P, F_2)) == 2a",
    "E20": "Distance(P, F_1) + Distance(P, F_2) == 2a",
    "E21": "A_{arbelos} == π (Distance(C, D) / 2)^2",
    "E22": "A_{salinon} = π (d / 2)^2",
    "E23": "A_{inner} = (1/2) A_{outer}",
    "E24": "3 < π < 2sqrt(3)",
    "E25": "Distance(P, A) Distance(P, B) == Distance(P, C) Distance(P, D)",
    "E26": "AreCollinear(D, E, F)",
    "E27": "{AreConcyclic(A, E, F, M), AreConcyclic(B, F, D, M), AreConcyclic(C, D, E, M)}",
    "E28": "Min(Angle(A, C, B), Angle(B, C, A)) == 90°",
    "E29": "{ArePerpendicular(Line(O, M), Line(A, B)), Distance(A, M) == Distance(M, B)}",
    "E30": "ArePerpendicular(Line(O, T), t)",
    "E31": "y = 2a x - a^2",
    "E32": "(1/2) (2t) (2 / t) = 2",
    "E33": "Distance(A, F) == Distance(F, B) + Distance(B, C)",
    "E34": "1 / sqrt(r) = 1 / sqrt(r_1) + 1 / sqrt(r_2)",
    "E35": "t = 2sqrt(r_1 r_2)",
    "E36": "A = (1/2) (π - sqrt(3)) s^2",
    "E37": "Distance(P, A) / Distance(P, B) == k",
    "E38": "ArePerpendicular(Line(O_1, O_2), Line(A, B))",
    "E39": "Distance(A, B) == 2r sin(θ / 2)",
    "E40": "{Angle(A, P, B) == Angle(A, Q, B), AreConcyclic(A, B, P, Q)}",

    # ---- F. Triangles and polygons
    "F1": "A + B + C = 180°",
    "F2": "γ_{ext} = α + β",
    "F3": "S = (n - 2) 180°",
    "F4": "Sum(γ_{ext}) == 360°",
    "F5": "A = (1/2) b h",
    "F6": "Distance(A, G) / Distance(G, M) == 2",
    "F7": "d_1 + d_2 + d_3 = h",
    "F8": "Area(M_1, M_2, M_3, M_4) == (1/2) Area(A, B, C, D)",
    "F9": "{Distance(N_1, N_2) == Distance(N_2, N_3), Distance(N_2, N_3) == Distance(N_3, N_1)}",
    "F10": "(Distance(B, D) / Distance(D, C)) (Distance(C, E) / Distance(E, A)) (Distance(A, F) / Distance(F, B)) == 1",
    "F11": "A = I + B / 2 - 1",
    "F12": "A = b h",
    "F13": "A = (1/2) (a + b) h",
    "F14": "A = (1/2) b h",
    "F15": "A = (1/2) d_1 d_2",
    "F16": "{A = r s, s = (a + b + c) / 2}",
    "F17": "{AreParallel(Line(M, N), Line(B, C)), Distance(M, N) == (1/2) Distance(B, C)}",
    "F18": "{Area(G, B, D) == Area(A, B, C) / 6, Area(G, D, C) == Area(A, B, C) / 6, Area(G, C, E) == Area(A, B, C) / 6, Area(G, E, A) == Area(A, B, C) / 6, Area(G, A, F) == Area(A, B, C) / 6, Area(G, F, B) == Area(A, B, C) / 6}",
    "F19": "Distance(B, D) / Distance(D, C) == Distance(A, B) / Distance(A, C)",
    "F20": "AreConcurrent(Line(A, D), Line(B, E), Line(C, F))",
    "F21": "{Distance(O, A) == Distance(O, B), Distance(O, B) == Distance(O, C)}",
    "F22": "{Distance(I, Line(A, B)) == Distance(I, Line(B, C)), Distance(I, Line(B, C)) == Distance(I, Line(C, A))}",
    "F23": "Distance(H, G) == 2Distance(G, O)",
    "F24": "R_9 = R / 2",
    "F25": "(Distance(A, F) / Distance(F, B)) (Distance(B, D) / Distance(D, C)) (Distance(C, E) / Distance(E, A)) == 1",
    "F26": "{Distance(A, B) == Distance(A, C), Min(Angle(A, B, C), Angle(C, B, A)) == Min(Angle(B, C, A), Angle(A, C, B))}",
    "F27": "α_1 + α_2 + α_3 + α_4 + α_5 = 180°",
    "F28": "A = (1/2) p a",
    "F29": "A = sqrt(3) s^2 / 4",
    "F30": "A = 3sqrt(3) s^2 / 2",
    "F31": "{Min(Angle(A, P, B), Angle(B, P, A)) == 120°, Min(Angle(B, P, C), Angle(C, P, B)) == 120°, Min(Angle(C, P, A), Angle(A, P, C)) == 120°}",
    "F32": "Area(D, E, F) == (1/7) Area(A, B, C)",
    "F33": "{k (n - 2) 180° / n = 360°, n ∈ {3, 4, 6}}",
    "F34": "a + c = b + d",
    "F35": "{Distance(P, R) == Distance(Q, S), ArePerpendicular(Line(P, R), Line(Q, S))}",
    "F36": "{Distance(P, Q) == Distance(Q, R), Distance(Q, R) == Distance(R, S), Distance(R, S) == Distance(S, P), ArePerpendicular(Line(P, Q), Line(Q, R))}",
    "F37": "{Distance(P, Q) == Distance(Q, R), Distance(Q, R) == Distance(R, P)}",
    "F38": "Area(D, E, F) == (1/4) Area(A, B, C)",
    "F39": "Area(T) == (1/2) Area(P)",
    "F40": "{Distance(A, O) == Distance(O, C), Distance(B, O) == Distance(O, D)}",
    "F41": "Area(flank) == Area(A, B, C)",
    "F42": "A = 2 (1 + sqrt(2)) s^2",
    "F43": "A = 3r^2",
    "F44": "A + B + C = 180°",
    "F45": "{AreParallel(Line(D, E), Line(B, C)), Distance(A, D) / Distance(D, B) == Distance(A, E) / Distance(E, C)}",
    "F46": "{Min(Angle(A, C, O), Angle(O, C, A)) == 45°, Min(Angle(O, C, B), Angle(B, C, O)) == 45°}",
    "F47": "s = a b / (a + b)",
    "F48": "Area(A, O, D) == Area(B, O, C)",
    "F49": "Area(P, A, B) + Area(P, C, D) == (1/2) Area(A, B, C, D)",
    "F50": "{ArePerpendicular(Line(E, M), Line(B, C)), Distance(A, M) == Distance(M, D)}",
    "F51": "\"DE + EF + FD is minimal (the orthic triangle)\"",
    "F52": "{Distance(P, A) < Distance(P, B) + Distance(P, C), Distance(P, B) < Distance(P, C) + Distance(P, A), Distance(P, C) < Distance(P, A) + Distance(P, B)}",
    "F53": "Distance(P, A)^2 + Distance(P, C)^2 == Distance(P, B)^2 + Distance(P, D)^2",
    "F54": "b^2 m + c^2 n = a (d^2 + m n)",
    "F55": "m_a^2 = (2b^2 + 2c^2 - a^2) / 4",
    "F56": "A = sqrt(s (s - a) (s - b) (s - c))",
    "F57": "Sum(d(i), i, 1, n) = 2A / s",
    "F58": "Area(t_m) == (3/4) Area(A, B, C)",
    "F59": "{x = s - a, y = s - b, z = s - c}",
    "F60": "Area(A, B, E) == Area(A, D, G)",
    "F61": "{Distance(M, B) == Distance(M, I), Distance(M, I) == Distance(M, C)}",
    "F62": "AreConcyclic(A, B, C, H_a)",
    "F63": "Area(hexagon) == (2/3) Area(A, B, C)",
    "F64": "α + β + γ + δ = 360°",
    "F65": "A = (1/2) b h",
    "F66": "Distance(E, B) / Distance(E, C) == Distance(A, B) / Distance(A, C)",

    # ---- G. Trigonometry
    "G1": "sin(θ)^2 + cos(θ)^2 = 1",
    "G2": "sin(A + B) = sin(A) cos(B) + cos(A) sin(B)",
    "G3": "cos(A + B) = cos(A) cos(B) - sin(A) sin(B)",
    "G4": "sin(2θ) = 2sin(θ) cos(θ)",
    "G5": "{a / sin(A) = b / sin(B), b / sin(B) = c / sin(C), c / sin(C) = 2R}",
    "G6": "A = (1/2) a b sin(C)",
    "G7": "tan(θ / 2) = sin(θ) / (1 + cos(θ))",
    "G8": "sin(A - B) = sin(A) cos(B) - cos(A) sin(B)",
    "G9": "cos(A - B) = cos(A) cos(B) + sin(A) sin(B)",
    "G10": "tan(A + B) = (tan(A) + tan(B)) / (1 - tan(A) tan(B))",
    "G11": "{cos(2θ) = 2cos(θ)^2 - 1, 2cos(θ)^2 - 1 = 1 - 2sin(θ)^2}",
    "G12": "{sin(θ / 2)^2 = (1 - cos(θ)) / 2, cos(θ / 2)^2 = (1 + cos(θ)) / 2}",
    "G13": "sin(A) + sin(B) = 2sin((A + B) / 2) cos((A - B) / 2)",
    "G14": "{1 + tan(θ)^2 = sec(θ)^2, 1 + cot(θ)^2 = csc(θ)^2}",
    "G15": "{cos(36°) = φ / 2, φ / 2 = (1 + sqrt(5)) / 4}",
    "G16": "atan(1) + atan(2) + atan(3) = π",
    "G17": "atan(1/2) + atan(1/3) = π / 4",
    "G18": "a = b cos(C) + c cos(B)",
    "G19": "{sin(x) < x < tan(x), 0 < x < π / 2}",
    "G20": "{sin(x) ≥ 2x / π, 0 ≤ x ≤ π / 2}",
    "G21": "a / sin(A) = b / sin(B)",
    "G22": "{sin(30°) = 1/2, sin(45°) = sqrt(2) / 2, sin(60°) = sqrt(3) / 2}",
    "G23": "{tan(15°) = 2 - sqrt(3), tan(75°) = 2 + sqrt(3)}",
    "G24": "A = n r^2 sin(2π / n) / 2",
    "G25": "{cos(θ) = (1 - t^2) / (1 + t^2), sin(θ) = 2t / (1 + t^2), t = tan(θ / 2)}",
    "G26": "asin(x) + acos(x) = π / 2",
    "G27": "sin(A + B) = sin(A) cos(B) + cos(A) sin(B)",
    "G28": "A = (1/2) d_1 d_2 sin(θ)",
    "G29": "sin(2θ) = 2sin(θ) cos(θ)",
    "G30": "sin(x) + cos(x) ≤ sqrt(2)",
    "G31": "a b c = 4R A",

    # ---- H. Calculus
    "H1": "Derivative(sin(θ), θ) = cos(θ)",
    "H2": "Integral(f(x), x, a, b) = Limit(Sum(f(a + i (b - a) / n) (b - a) / n, i, 1, n), n, ∞)",
    "H3": "Integral(x, x, 0, a) = a^2 / 2",
    "H4": "Integral(x^2, x, 0, a) = a^3 / 3",
    "H5": "Integral(1 / x, x, 1, a b) = Integral(1 / x, x, 1, a) + Integral(1 / x, x, 1, b)",
    "H6": "{Integral(f(u), u, u_1, u_2) + Integral(g(v), v, v_1, v_2) = u_2 v_2 - u_1 v_1, v_1 = f(u_1), v_2 = f(u_2), g(f(u)) = u}",
    "H7": "Derivative(cos(θ), θ) = -sin(θ)",
    "H8": "Derivative(x^2, x) = 2x",
    "H9": "Derivative(x^3, x) = 3x^2",
    "H10": "Derivative(u(x) v(x), x) = u(x) Derivative(v(x), x) + v(x) Derivative(u(x), x)",
    "H11": "Derivative(sqrt(x), x) = 1 / (2sqrt(x))",
    "H12": "Derivative(1 / x, x) = -1 / x^2",
    "H13": "Derivative(Integral(f(t), t, a, x), x) = f(x)",
    "H14": "f'(c) = (f(b) - f(a)) / (b - a)",
    "H15": "Limit(sin(x) / x, x, 0) = 1",
    "H16": "Integral(sin(x)^2, x, 0, π / 2) = π / 4",
    "H17": "Integral(ln(x), x, 1, a) = a ln(a) - a + 1",
    "H18": "Integral(x^n, x, 0, 1) + Integral(x^(1 / n), x, 0, 1) = 1",
    "H19": "A_1 = A_2",
    "H20": "Derivative(π r^2, r) = 2π r",
    "H21": "Derivative((4/3) π r^3, r) = 4π r^2",
    "H22": "{Integral(f(x), x, -a, a) = 0, f(-x) = -f(x)}",
    "H23": "Integral(f(x), x, a, b) = f(c) (b - a)",
    "H24": "A = 3π r^2",
    "H25": "{y = f(x), g(f(x)) = x, g'(y) = 1 / f'(x)}",
    "H26": "Integral(f(x), x, g(a), g(b)) = Integral(f(g(u)) g'(u), u, a, b)",
    "H27": "Derivative(ℯ^x, x) = ℯ^x",
    "H28": "Integral(sin(θ), θ, 0, π) = 2",
    "H29": "1 - cos(x) ≤ x^2 / 2",
    "H30": "Derivative(tan(θ), θ) = sec(θ)^2",
    "H31": "s'(t) = sqrt(X'(t)^2 + Y'(t)^2)",
    "H32": "Derivative(atan(x), x) = 1 / (1 + x^2)",

    # ---- I. Solids
    "I1": "V = h (a^2 + a b + b^2) / 3",
    "I2": "V = π r^2 h / 3",
    "I3": "{V = π r^2 (2r) - 2 (1/3) π r^2 r, π r^2 (2r) - 2 (1/3) π r^2 r = (4/3) π r^3}",
    "I4": "S = 4π r^2",
    "I5": "d^2 = a^2 + b^2 + c^2",
    "I6": "A_1^2 + A_2^2 + A_3^2 = A_4^2",
    "I7": "V = B h / 3",
    "I8": "V = 16r^3 / 3",
    "I9": "V = π h^3 / 6",
    "I10": "V - E + F = 2",
    "I11": "S = π r l",
    "I12": "V = B h",
    "I13": "V = B h / 3",
    "I14": "V = B h / 3",
    "I15": "{V = r S / 3, r S / 3 = (4/3) π r^3}",
    "I16": "V = 2π R π r^2",
    "I17": "{V = a^3 - 4 (a^3 / 6), a^3 - 4 (a^3 / 6) = a^3 / 3}",
    "I18": "1 / m + 1 / n > 1/2",
    "I19": "A = (α + β + γ - π) r^2",
    "I20": "V = 2a^3",
    "I21": "Sum(δ_v) == 720°",
    "I22": "V = a^3 / 6",
    "I23": "S = 2π r h + 2π r^2",
    "I24": "Distance(P, F_1) + Distance(P, F_2) == 2a",
    "I25": "{V - E + F = 2, p = 12}",
    "I26": "Limit((20/27)^n, n, ∞) = 0",
    "I27": "Limit(Sum(k^2, k, 1, n) / n^3, n, ∞) = 1/3",

    # ---- J. Number theory, irrationality, curios
    "J1": "\"√2 ∉ ℚ\"",
    "J2": "{φ^2 = φ + 1, φ = (1 + sqrt(5)) / 2}",
    "J3": "ContinuedFraction((1 + sqrt(5)) / 2)",
    "J4": "h_n = sqrt(n)",
    "J5": "BinomialCoefficient(n, 2) = n (n - 1) / 2",
    "J6": "Sum(BinomialCoefficient(m, k) BinomialCoefficient(n, r - k), k, 0, r) = BinomialCoefficient(m + n, r)",
    "J7": "A_{odd} = A_{even}",
    "J8": "3/8 ≠ 2/5",
    "J9": "\"[P] = [Q] ⇒ P ∼ Q\"",
    "J10": "(2k + 1)^2 + (2k^2 + 2k)^2 = (2k^2 + 2k + 1)^2",
    "J11": "\"√3 ∉ ℚ\"",
    "J12": "\"φ ∉ ℚ\"",
    "J13": "Mod(a^p - a, p) == 0",
    "J14": "{Mod(p, 4) == 1, p == x^2 + (2y)^2}",
    "J15": "GCD(a, b) == GCD(b, a - b)",
    "J16": "d / s = φ",
    "J17": "(10a + 5)^2 = 100a (a + 1) + 25",
    "J18": "2 ≠ sqrt(2)",
    "J19": "\"|ℚ| = |ℕ|\"",
    "J20": "(m^2 - n^2)^2 + (2m n)^2 = (m^2 + n^2)^2",
    "J21": "N = GCD(a, b) - 1",
    "J22": "sqrt(3) s^2 / 4 = x^2",
    "J23": "{p > 3, Mod(p, 6) == 1 ∨ Mod(p, 6) == 5}",
    "J24": "(Mod(Divisors(n), 2) == 1) == (floor(sqrt(n))^2 == n)",
    "J25": "ContinuedFraction(sqrt(2))",
    "J26": "Distance(A, B) ≠ Distance(A, C)",
    "J27": "8^2 = 5 * 13 - 1",
    "J28": "\"gcd(m, n) = 1 ⇒ ℤ_{mn} ≅ ℤ_m × ℤ_n\"",
    "J29": "\"∑_{d | n} φ(d) = n\"",
    "J30": "b c - a d = 1",
    "J31": "{(2j + 1) + (2k + 1) = 2 (j + k + 1), (2j + 1) (2k + 1) = 2 (2j k + j + k) + 1}",
    "J32": "d^2 = 2s^2",
    "J33": "\"n ≡ digit sum(n) (mod 9)\"",

    # ---- K. Counting and probability
    "K1": "N = BinomialCoefficient(m + n, m)",
    "K2": "BinomialCoefficient(n, k) = BinomialCoefficient(n - 1, k - 1) + BinomialCoefficient(n - 1, k)",
    "K3": "BinomialCoefficient(n, k) = BinomialCoefficient(n, n - k)",
    "K4": "Sum(BinomialCoefficient(n, k)^2, k, 0, n) = BinomialCoefficient(2n, n)",
    "K5": "{C_n = BinomialCoefficient(2n, n) - BinomialCoefficient(2n, n + 1), BinomialCoefficient(2n, n) - BinomialCoefficient(2n, n + 1) = BinomialCoefficient(2n, n) / (n + 1)}",
    "K6": "{t(n) = t(n - 1) + t(n - 2), t(n) = F(n + 1)}",
    "K7": "F(m + n) = F(m) F(n + 1) + F(m - 1) F(n)",
    "K8": "BinomialCoefficient(n + k - 1, k - 1)",
    "K9": "D = n (n - 3) / 2",
    "K10": "R_n = 1 + BinomialCoefficient(n, 2) + BinomialCoefficient(n, 4)",
    "K11": "30 ≠ 32",
    "K12": "Mod(4^n - 1, 3) == 0",
    "K13": "Length(Union(Union(A, B), C)) == Length(A) + Length(B) + Length(C) - Length(Intersection(A, B)) - Length(Intersection(B, C)) - Length(Intersection(C, A)) + Length(Intersection(Intersection(A, B), C))",
    "K14": "{N = Sum((n - k + 1)^2, k, 1, n), Sum((n - k + 1)^2, k, 1, n) = Sum(k^2, k, 1, n)}",
    "K15": "BinomialCoefficient(n + 1, 2)^2",
    "K16": "R_n = 1 + n + BinomialCoefficient(n, 2)",
    "K17": "BinomialCoefficient(n + 1, 2) = Sum(k, k, 1, n)",
    "K18": "\"R(3, 3) = 6\"",
    "K19": "Sum(BinomialCoefficient(n - k, k), k, 0, floor(n / 2)) = F(n + 1)",
    "K20": "Sum(deg_v) == 2E",
    "K21": "{P = 1 - (3/4)^2, 1 - (3/4)^2 = 7/16}",
    "K22": "d ≤ sqrt(2) / 2",
    "K23": "(a + b)^n = Sum(BinomialCoefficient(n, k) a^(n - k) b^k, k, 0, n)",
    "K24": "P ∈ {1/3, 1/2, 1/4}",
    "K25": "Sum(k BinomialCoefficient(n, k), k, 0, n) = n 2^(n - 1)",
    "K26": "{Sum((-1)^k BinomialCoefficient(n, k), k, 0, n) = 0, n ≥ 1}",
    "K27": "P = 1/4",
    "K28": "P = 1/4",
    "K29": "\"max_H |H ∩ S| ≥ 4\"",
    "K30": "\"p(n, ≤ k parts) = p(n, parts ≤ k)\"",
    "K31": "\"#{λ = λ'} = #{distinct odd parts}\"",
    "K32": "\"p(n | distinct) = p(n | odd)\"",

    # ---- L. Vectors, matrices, complex numbers
    "L1": "(u_1, u_2) + (v_1, v_2) = (v_1, v_2) + (u_1, u_2)",
    "L2": "{(u_1, u_2) * (v_1, v_2) = u_1 v_1 + u_2 v_2, u_1 v_1 + u_2 v_2 = abs((u_1, u_2)) abs((v_1, v_2)) cos(θ)}",
    "L3": "area = a d - b c",
    "L4": "A = Sum(X(i) Y(i + 1) - X(i + 1) Y(i), i, 1, n) / 2",
    "L5": "x = Determinant({{c_1, b_1}, {c_2, b_2}}) / Determinant({{a_1, b_1}, {a_2, b_2}})",
    "L6": "{abs(z w) = abs(z) abs(w), arg(z w) = arg(z) + arg(w)}",
    "L7": "Sum(ℯ^(2π ί k / n), k, 0, n - 1) = 0",
    "L8": "d = abs(a x_0 + b y_0 + c) / sqrt(a^2 + b^2)",
    "L9": "Reflect(Reflect(P, l_1), l_2) == Rotate(P, 2θ, O)",
    "L10": "Area(ApplyMatrix(T, S)) == abs(Determinant(T)) Area(S)",
    "L11": "R S ≠ S R",
    "L12": "(u_1, u_2) * ((v_1, v_2) + (w_1, w_2)) = (u_1, u_2) * (v_1, v_2) + (u_1, u_2) * (w_1, w_2)",
    "L13": "{{{cos(θ), -sin(θ)}, {sin(θ), cos(θ)}} (1, 0) = (cos(θ), sin(θ)), {{cos(θ), -sin(θ)}, {sin(θ), cos(θ)}} (0, 1) = (-sin(θ), cos(θ))}",
    "L14": "{{cos(B), -sin(B)}, {sin(B), cos(B)}} {{cos(A), -sin(A)}, {sin(A), cos(A)}} = {{cos(A + B), -sin(A + B)}, {sin(A + B), cos(A + B)}}",
    "L15": "Determinant(T S) == Determinant(T) Determinant(S)",
}

# entries that are only a GeoGebra text object (no GeoGebra notation exists)
TEXT_ONLY = frozenset(k for k, v in GEOGEBRA.items() if v.startswith('"'))
